"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _dashboard_shell from './dashboard-shell.bones.json'
import _route_panel from './route-panel.bones.json'

registerBones({
  "dashboard-shell": _dashboard_shell,
  "route-panel": _route_panel,
})
